### ISSUE TITLE
REQUEST: Show accuracy display on Expedition Success/Failed screen

### ISSUE THREAD

**Issue by JarheadHME** [Tuesday1028/GTFO_AccuracyTracker#1]
Some way to see what everyone's accuracy was in the recently finished run would be very nice. Else to see it after the fact, I must check a video recording

**Comment by JarheadHME** [comment]
Bump.

I'm wondering if you're working on this. If not, I may make an attempt to implement it myself. I don't wish to do work that you are already doing, though. Thanks.

**Comment by Mamizu1028** [comment]
> Bump.
> 
> I'm wondering if you're working on this. If not, I may make an attempt to implement it myself. I don't wish to do work that you are already doing, though. Thanks.

I'm so sorry, I don't have time to update these mods at the moment, I will update them when TheArchive releases the next release.

**Comment by Mamizu1028** [comment]
Done
