### ISSUE TITLE
Add more settings for the ExpeditionSuccess screen accuracy display

### ISSUE THREAD

**Issue by JarheadHME** [Tuesday1028/GTFO_AccuracyTracker#3]
![image](https://github.com/Tuesday1028/GTFO_AccuracyTracker/assets/15879336/2ad51a9e-2258-45e0-a1fb-9bb2a8343201)
![image](https://i.imgur.com/V1jPIuZ.png)

(Not the default)

I'm not making a Pull Request for this, because I've also translated everything to English for my own usage. But here is the commit with the changes I made: https://github.com/JarheadHME/GTFO_AccuracyTracker/commit/d31eeff8ff72476f8ef53c22184c2779d0e86ef3

You may also use this as suggested translations for the settings to if you wish, once that finally gets merged into archive. 

Also, I suspect linking the format setting to `AccuracyUpdater` may have been unnecessary, but I am lazy so I didn't check properly.

**Comment by Mamizu1028** [comment]
completed
