### ISSUE TITLE
Weakpoint Penetration shots count each hit

### ISSUE THREAD

**Issue by JarheadHME** [Tuesday1028/GTFO_AccuracyTracker#5]
Body hits count properly, but hitting heads will count multiple.

https://github.com/Tuesday1028/GTFO_AccuracyTracker/assets/15879336/8f638f2b-95e8-41b6-8bfc-1aded681b031

https://github.com/Tuesday1028/GTFO_AccuracyTracker/assets/15879336/5a48ee6e-fdad-403e-bdc1-0d87f09abfd1

**Comment by Tuesday1028** [comment]
I will check when i have time.

**Comment by Mamizu1028** [comment]
The problem of the number of hits on weak points being counted multiple times should be fixed in this commit.
> https://github.com/Tuesday1028/GTFO_AccuracyTracker/commit/21b0d667cd8304e50aaba8dc9514548810f3ff59

**Comment by JarheadHME** [comment]
It seems to just about refuse to increase the weak point hits counter at all now
There now seems to be some very strange behavior with the weak points hit counter. If you just shoot the head, it doesn't count, but if you miss first BEFORE shooting the head, then it works. 

https://github.com/Tuesday1028/GTFO_AccuracyTracker/assets/15879336/08e7eb79-7744-48ba-8104-ca0ffbc0611f

**Comment by Mamizu1028** [comment]
I will fix this bug later today. (About 12 hours later)

**Comment by Mamizu1028** [comment]
The latest commit may fix this bug.

**Comment by JarheadHME** [comment]
This seems to work a bit better, but it seems to only count as a weakpoint hit if the first contact was counted.

https://github.com/Tuesday1028/GTFO_AccuracyTracker/assets/15879336/29a823ff-f633-4728-b04b-40a9052dce42

**Comment by Mamizu1028** [comment]
> This seems to work a bit better, but it seems to only count as a weakpoint hit if the first contact was counted.
> 
> https://github.com/Tuesday1028/GTFO_AccuracyTracker/assets/15879336/29a823ff-f633-4728-b04b-40a9052dce42

I will check it later

**Comment by Mamizu1028** [comment]
try latest build

**Comment by JarheadHME** [comment]
Seems to be all good!
