### ISSUE TITLE
(Minor) Display swaps two colors when no shots have been fired

### ISSUE THREAD

**Issue by JarheadHME** [Tuesday1028/GTFO_AccuracyTracker#6]
Only noticed this after playing R7C3 tonight after the update released.

This is normal color orders: 
![image](https://github.com/Tuesday1028/GTFO_AccuracyTracker/assets/15879336/0ac25e62-01f3-4cd2-9a34-ef64c1b65d35)

This is what it shows when no shots have been fired: 
![image](https://github.com/Tuesday1028/GTFO_AccuracyTracker/assets/15879336/4ea0315a-f7f7-42d4-8349-7c26cde126ba)

The colors are as followed: 
* Green = Hit ratio and shots hit (`HittedColor`)
* Red = Weakspot hit ratio and weakspot hits (`WeakspotHittedColor`)
* Normal/Gray = Shots Fired

Notice how in the first image, it shows `WeakspotHittedColor` BEFORE `HittedColor`. 
Then when no shots have been fired, these two are flipped when showing `TotalWeakspotHitted` and `TotalHitted`

**Comment by Mamizu1028** [comment]
Fixed
